### ISSUE TITLE
Reproduce in local?

### ISSUE THREAD

**Issue by shunkakinoki** [jameswenzel/bound-layerable#1]
Thank you for the wonderful repo!
Layered NFTs feel so unexplored yet soooo interesting, this is crazy. Appreciate sharing your knowledge - I tried reproducing it on my local computer with `hot-chain-svg`, it didn't produce an output.

Feel free to destroy this if repo is wip

**Comment by emo-eth** [comment]
Thanks for the kind words!! 
I had to do some very hacky stuff to get `hot-chain-svg` working when prototyping (like copying it into the source folder, as you can see), so it's probably very broken. Let me see if I can get that fixed.
